FROM alpine
RUN apk add telegraf --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted --no-cache
RUN apk add influxdb openrc supervisor
COPY ./srcs/telegraf.conf /etc/telegraf/telegraf.conf
COPY ./srcs/entry_point.sh /
COPY ./srcs/supervisord.conf /etc/
EXPOSE 8086
CMD sh entry_point.sh