FROM alpine:3.11
RUN apk add telegraf --repository http://dl-3.alpinelinux.org/alpine/edge/community/ --allow-untrusted --no-cache
RUN apk add influxdb openrc
COPY ./srcs/check_procces.sh /
COPY ./srcs/telegraf.conf /etc/telegraf/telegraf.conf
COPY ./srcs/entry_point.sh /
EXPOSE 8086
CMD sh entry_point.sh