version: "3"
services: 
    db:
        build: ./mysql
        ports: 
            - "3306:3306"
    phpmyadmin:
        build: ./phpmyadmin
        ports:
            - "80:80"
            - "443:443"
            - "5000:5000"
        links: 
            - db