apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps-service
  labels:
    app: ftps
spec:
  type: LoadBalancer
  ports:
    - port: 21
      targetPort: 21
      nodePort: 21
      name: main-port
    - port: 21000
      targetPort: 21000
      nodePort: 21000
      name: passive-port
  selector:
    app: ftps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - image: ftps-service
        name: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 21000
        