apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps-service
  labels:
    app: ftps
spec:
  type: LoadBalancer
  ports:
    - port: 21
      targetPort: 21
      nodePort: 21
      name: main-port
    - port: 21000
      targetPort: 21000
      nodePort: 21000
      name: passive-port0
    - port: 21001
      targetPort: 21001
      nodePort: 21001
      name: passive-port1
    - port: 21002
      targetPort: 21002
      nodePort: 21002
      name: passive-port2
    - port: 21003
      targetPort: 21003
      nodePort: 21003
      name: passive-port3
    - port: 21004
      targetPort: 21004
      nodePort: 21004
      name: passive-port4
    - port: 21005
      targetPort: 21005
      nodePort: 21005
      name: passive-port5
    - port: 21006
      targetPort: 21006
      nodePort: 21006
      name: passive-port6
    - port: 21007
      targetPort: 21007
      nodePort: 21007
      name: passive-port7
    - port: 21008
      targetPort: 21008
      nodePort: 21008
      name: passive-port8
    - port: 21009
      targetPort: 21009
      nodePort: 21009
      name: passive-port9
  selector:
    app: ftps
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-pv-claim
  labels:
    app: ftps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - image: ftps-service
        name: ftps
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - /check_procces.sh
          initialDelaySeconds: 10
          periodSeconds: 5
        ports:
        - containerPort: 21
        - containerPort: 21000
        - containerPort: 21001
        - containerPort: 21002
        - containerPort: 21003
        - containerPort: 21004
        - containerPort: 21005
        - containerPort: 21006
        - containerPort: 21007
        - containerPort: 21008
        - containerPort: 21009
        volumeMounts:
        - name: ftps-persistent-storage
          mountPath: /root/
      volumes:
      - name: ftps-persistent-storage
        persistentVolumeClaim:
          claimName: ftps-pv-claim
        