apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: grafana-service
  labels:
    app: grafana
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 3000
      name: https
  selector:
    app: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: grafana-service
        name: grafana
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - /check_procces.sh
          initialDelaySeconds: 10
          periodSeconds: 5
        ports:
        - containerPort: 3000