apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: phpmyadmin
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 5000
  selector:
    app: phpmyadmin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phpmyadmin-pv-claim
  labels:
    app: phpmyadmin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - image: phpmyadmin-service
        name: phpmyadmin
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          name: phpmyadmin
        env:
          - name: PMA_HOST
            value: 'mysql-service'
          - name: PMA_PORT
            value: '3306'
          - name: MYSQL_ROOT_PASSWORD
            value: '1234PO'
          - name: PMA_USER
            value: 'hamza'
        volumeMounts:
        - name: phpmyadmin-persistent-storage
          mountPath: /var/lib/phpmyadmin
      volumes:
      - name: phpmyadmin-persistent-storage
        persistentVolumeClaim:
          claimName: phpmyadmin-pv-claim