FROM alpine

RUN apk update
RUN apk add --no-cache mariadb mariadb-client openrc supervisor
RUN apk add telegraf --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted --no-cache

COPY ./srcs/setup.sh /
COPY ./srcs/entry_point.sh /
COPY ./srcs/my.cnf /etc/mysql/my.cnf
COPY ./srcs/wordpress_db.sql /
COPY ./srcs/telegraf.conf /etc/telegraf/telegraf.conf
COPY ./srcs/supervisord.conf /etc

EXPOSE 3306
CMD sh setup.sh