FROM alpine:3.11

RUN apk update
RUN apk add --no-cache mariadb mariadb-client openrc
RUN apk add telegraf --repository http://dl-3.alpinelinux.org/alpine/edge/community/ --allow-untrusted --no-cache

COPY ./srcs/check_procces.sh /
COPY ./srcs/entry_point.sh /
COPY ./srcs/my.cnf /etc/mysql/my.cnf
COPY ./srcs/wordpress_db.sql /
COPY ./srcs/telegraf.conf /etc/telegraf/telegraf.conf

EXPOSE 3306
CMD sh entry_point.sh