FROM alpine

RUN apk update
RUN apk add --no-cache mariadb mariadb-client
RUN apk add telegraf --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted --no-cache

COPY ./srcs/setup.sh /tmp
COPY ./srcs/my.cnf /etc/mysql/my.cnf
COPY ./srcs/wordpress_db.sql /
# #COPY ./telegraf.conf /etc/telegraf/telegraf.conf

EXPOSE 3306

CMD sh /tmp/setup.sh
#CMD sh entry_point.sh