FROM alpine
RUN apk add telegraf --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted --no-cache
RUN apk add grafana --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted --no-cache
RUN apk add openrc vim
COPY ./srcs/telegraf.conf /etc/telegraf/telegraf.conf
COPY ./srcs/start.sh /
COPY ./srcs/grafana.db /
COPY ./srcs/grafana.db /usr/share/grafana/data/
EXPOSE 3000
CMD sh start.sh